### ISSUE TITLE
version is falling behind

### ISSUE THREAD

**Issue by lightyear15** [alexmurray/golangci-lint-snap#1]
golangci-lint is currently at version 1.41.1
while snapcraft version is stuck at 1.29.0

Time to rebuild the snapcraft and maybe thinking about automating the rebuild whenever there is a new version.
Please consider, releasing snapcrafts for official golangci-lint tagged releases in the `stable` channel

**Comment by alexmurray** [comment]
Thanks for bringing this to my attention - I have just pushed an update so it should auto-build from 1.41.1 for now and will make sure I stay on top of future releases (there is not an easy way to do this automatically at this stage).

**Comment by alexmurray** [comment]
Closing this as the snap is still kept up-to-date.
